---
driver:
  name: vagrant
  customize:
    memory: 12000

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing
  # environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 13
  # Copy secret to /tmp/kitchen on test VM. Kitchen tries to gather secrets
  # before any recipes had a chance to run -> we cannot use a recipe to put the
  # secrets file in place.
  encrypted_data_bag_secret_key_path: .chef/encrypted_data_bag_secret

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.4

suites:
  - name: default
    run_list:
      # run_list taken from roles/allinone.json
      - recipe[openstack-common]
      - recipe[openstack-common::logging]
      - recipe[openstack-common::sysctl]
      - recipe[openstack-common::client]
      - recipe[openstack-ops-database::server]
      - recipe[openstack-ops-database::openstack-db]
      - recipe[openstack-ops-messaging::rabbitmq-server]
      - recipe[openstack-identity::server-apache]
      - recipe[openstack-identity::registration]
      - recipe[openstack-identity::openrc]
      - recipe[openstack-image::api]
      - recipe[openstack-image::registry]
      - recipe[openstack-image::identity_registration]
      - recipe[openstack-network::identity_registration]
      - recipe[openstack-network::ml2_core_plugin]
      - recipe[openstack-network::ml2_openvswitch]
      - recipe[openstack-network]
      - recipe[openstack-network::openvswitch]
      - recipe[openstack-network::_bridge_config_example]
      - recipe[openstack-network::plugin_config]
      - recipe[openstack-network::server]
      - recipe[openstack-network::l3_agent]
      - recipe[openstack-network::dhcp_agent]
      - recipe[openstack-network::metadata_agent]
      - recipe[openstack-network::openvswitch_agent]
      - recipe[openstack-compute::nova-setup]
      - recipe[openstack-compute::identity_registration]
      - recipe[openstack-compute::conductor]
      - recipe[openstack-compute::api-os-compute]
      - recipe[openstack-compute::api-metadata]
      - recipe[openstack-compute::placement_api]
      - recipe[openstack-compute::scheduler]
      - recipe[openstack-compute::vncproxy]
      - recipe[openstack-compute::compute]
      - recipe[openstack-compute::identity_registration]
      # NOTE: block-storage, orchestration, dashboard, etc. can be installed
      #       but are not tested by tempest
      - recipe[openstack-block-storage::api]
      - recipe[openstack-block-storage::scheduler]
      - recipe[openstack-block-storage::volume_driver_lvm]
      - recipe[openstack-block-storage::volume]
      - recipe[openstack-block-storage::backup]
      - recipe[openstack-block-storage::identity_registration]
      - recipe[openstack-orchestration::engine]
      - recipe[openstack-orchestration::api]
      - recipe[openstack-orchestration::api-cfn]
      - recipe[openstack-orchestration::api-cloudwatch]
      - recipe[openstack-orchestration::identity_registration]
      - recipe[openstack-image::image_upload]
      - recipe[openstack-dashboard::horizon]
      - recipe[openstack-dashboard::neutron-lbaas-dashboard]
      - recipe[openstack-integration-test::create_network]
      - recipe[openstack-integration-test::setup]
      - recipe[openstack-integration-test::run_tempest]
    verifier:
      inspec_tests:
        - test/tempest/default
  # from environments/allinone-ubuntu16.json, environments/allinone-centos7.json
    attributes:
      # Attributes copied from environments/integration-ubuntu16.json
      apache:
        listen: []
      openstack:
        is_release: true
        apt:
          update_apt_cache: true
        dashboard:
          server_hostname: localhost
        memcached_servers: ['127.0.0.1:11211']
        telemetry:
          conf:
            DEFAULT:
              meter_dispatchers: database
        mq:
          user: admin
        network:
          conf:
            DEFAULT:
              service_plugins: router
        image:
          image_upload: true
        compute:
          conf:
            libvirt:
              cpu_type: none
              virt_type: qemu
        secret:
          key_path: /tmp/kitchen/encrypted_data_bag_secret
