site :opscode

cookbook 'apache2', '1.8.4'
cookbook 'apt', '2.3.8'
cookbook 'aws', '0.101.6'
cookbook 'build-essential', '1.4.2'
cookbook 'database', '1.5.2'
cookbook 'erlang'
cookbook 'memcached', '1.6.0'
cookbook 'mysql', '4.0.20'
cookbook 'openssl', '1.1.0'
cookbook 'postgresql', '3.1.0'
cookbook 'rabbitmq', '2.3.0'
cookbook 'xfs', '1.1.0'
cookbook 'yum', '~> 3.0'

cookbook 'openstack-block-storage', github: 'stackforge/cookbook-openstack-block-storage'
cookbook 'openstack-common', github: 'stackforge/cookbook-openstack-common'
cookbook 'openstack-compute', github: 'stackforge/cookbook-openstack-compute'
cookbook 'openstack-dashboard', github: 'stackforge/cookbook-openstack-dashboard'
cookbook 'openstack-identity', github: 'stackforge/cookbook-openstack-identity'
cookbook 'openstack-image', github: 'stackforge/cookbook-openstack-image'
cookbook 'openstack-network', github: 'stackforge/cookbook-openstack-network'
cookbook 'openstack-object-storage', github: 'stackforge/cookbook-openstack-object-storage'
cookbook 'openstack-ops-database', github: 'stackforge/cookbook-openstack-ops-database'
cookbook 'openstack-ops-messaging', github: 'stackforge/cookbook-openstack-ops-messaging'
cookbook 'openstack-orchestration', github: 'stackforge/cookbook-openstack-orchestration'
cookbook 'openstack-telemetry', github: 'stackforge/cookbook-openstack-telemetry'
