#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ntp', '1.1.8'
cookbook 'openssh', '0.8.0'
cookbook 'apt', '1.4.6'
cookbook 'yum', '0.6.2'
cookbook 'build-essential', '1.1.0'
cookbook 'erlang', '1.0.0'
cookbook 'openssl', '1.0.0'
cookbook 'postgresql', '0.99.4'
cookbook 'aws', '0.99.1'
cookbook 'xfs', '1.0.0'
cookbook 'database', '1.2.0'

cookbook 'mysql',
  :git => 'https://github.com/mattray/mysql.git',
  :ref => 'COOK-1384'

cookbook 'rabbitmq',
  :git => 'https://github.com/mattray/rabbitmq.git',
  :ref => 'COOK-1496'

cookbook 'sysctl',
  :git => 'https://github.com/mattray/sysctl.git'

cookbook 'osops-utils',
  :git => 'https://github.com/mattray/osops-utils.git'

cookbook 'keystone',
  :git => 'https://github.com/mattray/keystone.git',
  :ref => 'essex'

cookbook 'glance',
  :git => 'https://github.com/mattray/glance.git',
  :ref => 'essex'

cookbook 'nova',
  :git => 'https://github.com/mattray/nova.git',
  :ref => 'essex'

cookbook 'horizon',
  :git => 'https://github.com/mattray/horizon.git',
  :ref => 'essex'

# cookbook 'swift',
#   :git => 'https://github.com/mattray/swift.git',
#   :ref => 'essex'
