#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ntp', '1.2.0'
cookbook 'openssh', '1.0.0'
cookbook 'apt', '1.4.8'
cookbook 'yum', '0.8.2'
cookbook 'build-essential', '1.1.2'
cookbook 'erlang', '1.0.0'
cookbook 'openssl', '1.0.0'
cookbook 'postgresql', '1.0.0'
cookbook 'aws', '0.100.2'
cookbook 'xfs', '1.0.0'
cookbook 'database', '1.3.4'
cookbook 'mysql', '1.3.0'
cookbook 'rabbitmq', '1.6.2'

cookbook 'sysctl',
  :git => 'https://github.com/mattray/sysctl.git'

cookbook 'osops-utils',
  :git => 'https://github.com/mattray/osops-utils.git'

cookbook 'rabbitmq-openstack',
  :git => 'https://github.com/mattray/rabbitmq-openstack.git'

cookbook 'mysql-openstack',
  :git => 'https://github.com/mattray/mysql-openstack.git'

cookbook 'keystone',
  :git => 'https://github.com/mattray/keystone.git',
  :ref => 'essex'

cookbook 'glance',
  :git => 'https://github.com/mattray/glance.git',
  :ref => 'essex'

cookbook 'nova',
  :git => 'https://github.com/mattray/nova.git',
  :ref => 'essex'

cookbook 'horizon',
  :git => 'https://github.com/mattray/horizon.git',
  :ref => 'essex'

# cookbook 'swift',
#   :git => 'https://github.com/mattray/swift.git',
#   :ref => 'essex'
