* Roadmap
** docs
** rcbops iteration merge
** at&t pull requests
** osops-utils merges
** ohai dependencies
** nova-networking vlan support (jay pipes)
** enable floating IPs
   nova-manage floating create --ip_range=10.0.111.128/25
** lxc- calxeda
** Folsom
   Carl Perry's repos
   If you want to help out with the testing and reporting of bugs on your 12.04 servers,  you will want the following in your /etc/apt/sources.list:
   deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-proposed/folsom main
   If you just want to install the latest version of Openstack on your 12.04 servers, you will want the following in your /etc/apt/sources.list:
   deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/folsom main
   Please report any bugs that you discover on launchpad as well. In the coming months, we will be making it easier to use Openstack on both newer releases of Ubuntu and back porting those changes to 12.04 users as well.
** Quantum
   nicira & openvswitch from dreamhost
** Cinder
   DreamHost?/Ceph
** Swift

** PostgreSQL
   DreamHost & Qualcomm
** Hyper-V
   November at the OpenStack hack day
** HA OpenStack
   follow official documentation
   pacemaker cookbook, pacemaker_service LWRP
   Galera vs. MySQL MMR
   RabbitMQ clustered?
** Horizon-Skin cookbook
   after horizon removes the default skin, let's add a cookbook for passing a logo or something

** Ceilometer
** Baremetal
   calxeda working towards it
** RHEL
** IPv6
   DreamHost is doing this somewhat.
   Grizzly?
* Technical Debt
** nova::volume
   what's broken?
   /dev/sdb?
   apt-get install tgt open-iscsi open-iscsi-utils ?
   service tgt start?

** rabbitmq-server
   rename to "messaging" role
   waiting on 1.5.2 with http://tickets.opscode.com/browse/COOK-1496
   is rabbit too brittle? Is Qpid a better longterm solution?
   rackspace is sending a rabbitmq::distro recipe
** foodcritic all the cookbooks
   sure would be nice if you could turn off individual rules within a recipe
** TravisCI MVT testing
** Test-Kitchen
** mysql-master
   need to switch to using a "database" role and the database cookbook
   mysql having issues with 12.04 and omnibus
   is the cookbook too brittle? rackspace proposes a simplified replacement
   mmm-support or a slave recipe
** keystone
   removed monitoring
   understand use of osops
   why is there a sleep?
   tag and release 5.0.0
   gotta think Fog is a better solution to some of the Keystone manipulations
   need a keystone:client to wrap python-keystone,
   hopefully won't have to install keystone and specifically disable the service
** glance
   make a glance::client for other cookbooks
   refactor the glance/image upload in glance::api to use more idempotent Chef resources, perhaps as a separate recipe for readability
   run as the glance user instead of sudo
** osops-utils
   waiting for partial search
   need to document this thoroughly to explain purpose
   fix writing of etc/hosts to be idempotent
** nova config/setup
   needs cleanup to be safe to run partial Nova deploys
   nova-common should pass hashes instead of so many attributes, that would make conditional rendering blocks simpler
** nova::compute
   abstract out hypervisors and key off of attribute
   nova::network needs to move out
** nova::vncproxy
   needs to break out xen vs. kvm support
** swift
   compare with other implementations
   make documentation more consistent with other cookbooks
   tag and release 5.0.0
** there are a lot of :upgrades for packages rather than :install, let's clean that up.
** verify still need patch for nova-scheduler
** does search make sense for things like nova::common if you have 1000 compute nodes?
   would a data bag be cleaner? perhaps a notification handler that automatically updates it?
   as soon as the new search syntax is supported, switch to that (available now)
** Document source of packages for all repos and break out to make them interchangeable

** librarian-chef for spiceweasel
** remotefilemirror->pxe_dust and others?
** Should we add kong and exerstack to the repo so people can validate their deployments?
** Support multiple nova-network topologies
   right now just doing FlatDHCP
** base role
   remove validator.pem?
   chef-client?
** default security group
   enable SSH and ICMP ping
   euca-authorize -P tcp -s 192.168.1.1 -p 22 myservers
   euca-authorize -P icmp -s 192.168.1.1 -t -1:-1 myservers
** platform-family
   start using the node.platform_family for attribute gating
** OpenStack-Syslog/Monitoring
   pull the code back from Rackspace into 2 new cookbooks
   openstack-monitoring
   openstack-syslog
** osops-utils
   drop the , _, _ from searches and use the response["total"] instead of checking length
* Documentation
** Diagrams for Role/Cookbook relationships
   knife-spaghetti-roles
   Keystone
   Glance
   Nova
** Prerequisites for installation
   specifically with regards to network and operating system configuration
   lab-repo as a reference implementation
** Update the existing wiki documentation for Chef and OpenStack
** Chef for OpenStack QuickStart
** Desktop virtualization HOWTO
   document how to set all this up with Fusion/VirtualBox/Vagrant/KVM
** Alternate package HOWTO
** Testing Overview
