* CURRENT: QuickStart for Chef & OpenStack
** glance image loading
** rebase with rcbops and compare
** librarian-chef for spiceweasel
** QuickStart
* backlog
** remotefilemirror->pxe_dust and others?
** roles/cookbooks
*** base
    remove validator.pem?
    chef-client?
*** os-database
    document this
*** os-networks
    document this
*** osops-utils
    waiting for partial search
    need to document this thoroughly to explain purpose
    fix writing of etc/hosts to be idempotent
*** rabbitmq-server
    rename to "messaging" role
    waiting on 1.5.2 with http://tickets.opscode.com/browse/COOK-1496
    is rabbit too brittle? Is Qpid a better longterm solution?
    rackspace is sending a rabbitmq::distro recipe
*** mysql-master
    need to switch to using a "database" role and the database cookbook
    mysql having issues with 12.04 and omnibus
    is the cookbook too brittle? rackspace proposes a simplified replacement
*** keystone
    removed monitoring
    understand use of osops
    why is there a sleep?
    tag and release 5.0.0
    gotta think Fog is a better solution to some of the Keystone manipulations
    need a keystone:client to wrap
    package "python-keystone" do
    action :install
    end
*** glance
    make a glance::client for other cookbooks
*** nova config/setup
    needs cleanup to be safe to run partial Nova deploys
    nova-common should pass hashes instead of so many attributes, that would make conditional rendering blocks simpler
*** nova::compute
    abstract out hypervisors and key off of attribute
*** swift
    compare with other implementations
    make documentation more consistent with other cookbooks
    tag and release 5.0.0
** foodcritic all the cookbooks
   sure would be nice if you could turn off individual rules within a recipe
** Document source of packages for all repos and break out to make them interchangeable
** Diagrams for Role/Cookbook relationships
   knife-spaghetti-roles
   Keystone
   Glance
   Nova
* Roadmap
** knife-rackspace v2, via fog or openstack
** knife-hp, via fog or openstack
** Testing, testing, testing
** Folsom milestones
** XenServer support
** LXC support
** Hyper-V support
** PostgreSQL support
** Fedora support
** RHEL support
** Debian support
** OpenSuSE/SLES support
** IPv6 support
* Open Questions
** Do we planning on sticking with distro-repos and for how long? When and how do we start supporting Folsom milestones or source builds?
   move packages into nova-install recipe, key off of attribute to determine which technique to use to get all binaries in place used by other nova-* recipes (nova as example), source can be a version of this
   keep a node['openstack']['version'] and node['openstack']['previous_version'] for upgrades, also node['nova']['version'] and node['nova']['previous_version'] for component-specific versioning
** Are we deprecating supporting anything before Ubuntu 12.04/Debian 6/RHEL 6.2/Fedora 17?
** Do we want to use Environments for anything?
** Should we add kong and exerstack to the repo so people can validate their deployments?
** How agressive should we be on not supporting earlier versions of Chef and Chef Solo?
** What features do we NOT plan on supporting?
** We're going to want some CI and more testing for sure. FoodCritic, Test-Kitchen and TravisCI?
** does search make sense for things like nova::common if you have 1000 compute nodes?
   would a data bag be cleaner? perhaps a notification handler that automatically updates it?
   as soon as the new search syntax is supported, switch to that (available now)
* Technical Debt
  Rackspace->Rackspace US, Inc.
  there are a lot of :upgrades for packages rather than :install, let's clean that up.
  move the os-database and os-network attributes to an environment?
  verify still need patch for nova-scheduler
* Weekly Status 8/17
** Goals for next week:
*** nova and horizon deployed and working
*** document using librarian-chef to manage mix of community and github-based cookbooks
*** push openstack cookbooks to community site and Opscode github repos
*** start on the Quick Start for Chef and OpenStack
** DreamHost Chef for OpenStack Hackday August 21 in Los Angeles
** cookbooks
   Tracked with Librarian now
*** mysql - fork updated, waiting on new release with 12.04 omnibus well-supported COOK-1384
*** osops-utils - merged upstream, a few minor patches ahead for debugging
*** sysctl - new dep, need to get upstreamed
*** apt - released 1.4.6
*** rabbitmq - fix for COOK-1496
