* roles
** base
   remove validator.pem
   chef-client?
** os-database
   document this
** os-networks
   document this
** rabbitmq-server
   rename to "messaging" role
** mysql-master
   need to switch to using a "database" role and the database cookbook
** keystone
** glance
** nova config/setup
** nova::compute
** nova::scheduler
** nova::api
** nova::network
** nova::vncproxy
** nova::volume
** nova::project
** horizon
* cookbooks
** RabbitMQ
   http://tickets.opscode.com/browse/COOK-1386
   in the repo until this gets merged and released upstream
** MySQL
   since we're using the chef-full installer, we ran into the inability to use the mysql gem properly
   http://tickets.opscode.com/browse/COOK-1009
** Keystone
   remove monitoring
   understand use of osops
   why is there a sleep?
   tag and release 5.0.0
   gotta think Fog is a better solution to some of the Keystone manipulations
   switch default to client and move client code from nova/swift/glance/horizon
** OSOps
   should this be a data bag?
   need to read through this thoroughly to understand purpose
** Glance
   make a glance::client for other cookbooks
** Nova
   rabbit setup seems naive
   Break out hypervisor support into separate cookbooks
   tag and release 5.0.0
** Horizon
   tag and release 5.0.0
** Swift
   compare with Dell's implementation
   make documentation more consistent with other cookbooks
   tag and release 5.0.0
* foodcritic all the cookbooks
  bring in Etsy's rules too?
* Document source of packages for all repos and break out to make them interchangeable
* Diagrams for Role/Cookbook relationships
  Keystone
  Glance
  Nova
* Technical Debt
  Rackspace->Rackspace Hosting, Inc.
  merge RabbitMQ upstream
  merge MySQL upstream
  release and merge osops-utils
  there are a lot of :upgrades for packages rather than :install, let's clean that up.
* Open Questions
** Do we planning on sticking with distro-repos and for how long? When and how do we start supporting Folsom milestones or source builds?
** Are we deprecating supporting anything before Ubuntu 12.04/Debian 6/RHEL 6.2/Fedora 17?
** Do we want to use Environments for anything?
** Should we add kong and exerstack to the repo so people can validate their deployments?
** How agressive should we be on not supporting earlier versions of Chef and Chef Solo?
** What features do we NOT plan on supporting?
** We're going to want some CI and more testing for sure. FoodCritic, TravisCI and Jenkins?
** should we be using Chef-Librarian?
** does search make sense for things like nova::common if you have 1000 compute nodes?
   would a data bag be cleaner? perhaps a notification handler that automatically updates it?
   as soon as the new search syntax is supported, switch to that
* Roadmap
** first 5.0.0 tagged cookbooks
** QuickStart for Chef & OpenStack
** XenServer support
** LXC support
** Hyper-V support
** PostgreSQL support
** Fedora support
** RHEL support
** Debian support
** OpenSuSE/SLES support
** IPv6 support
