* Current Focus
** rebase with rcbops and compare
** fix labsetup to use proper network configuration
   I'm still having issues with the configuration of networking with my VMs but this appears to be related to configuration of my nova-compute hosts and will get documented in the prerequisites.
** glance-images
   use Cirros and optional Ubuntu 12.04
** nova::volume
   what's broken?
   /dev/sdb?
   apt-get install tgt open-iscsi open-iscsi-utils ?
   service tgt start?
** rabbitmq-server
   rename to "messaging" role
   waiting on 1.5.2 with http://tickets.opscode.com/browse/COOK-1496
   is rabbit too brittle? Is Qpid a better longterm solution?
   rackspace is sending a rabbitmq::distro recipe
** update cookbook dependencies
** work on making Spiceweasel interface with Librarian is also in progress.
* Technical Debt
** Rackspace->Rackspace US, Inc.
** determine what's up with services starting, restarting and enabling
** foodcritic all the cookbooks
   sure would be nice if you could turn off individual rules within a recipe
** TravisCI MVT testing
** Test-Kitchen
** mysql-master
   need to switch to using a "database" role and the database cookbook
   mysql having issues with 12.04 and omnibus
   is the cookbook too brittle? rackspace proposes a simplified replacement
** keystone
   removed monitoring
   understand use of osops
   why is there a sleep?
   tag and release 5.0.0
   gotta think Fog is a better solution to some of the Keystone manipulations
   need a keystone:client to wrap
   package "python-keystone" do
   action :install
   end
** glance
   make a glance::client for other cookbooks
   refactor the glance/image upload in glance::api to use more idempotent Chef resources, perhaps as a separate recipe for readability
** os-database
   document this
   move to Environment?
** os-networks
   document this
   move to Environment
** osops-utils
   waiting for partial search
   need to document this thoroughly to explain purpose
   fix writing of etc/hosts to be idempotent
** nova config/setup
   needs cleanup to be safe to run partial Nova deploys
   nova-common should pass hashes instead of so many attributes, that would make conditional rendering blocks simpler
** nova::compute
   abstract out hypervisors and key off of attribute
** swift
   compare with other implementations
   make documentation more consistent with other cookbooks
   tag and release 5.0.0
** there are a lot of :upgrades for packages rather than :install, let's clean that up.
** move the os-database and os-network attributes to an environment?
** verify still need patch for nova-scheduler
** does search make sense for things like nova::common if you have 1000 compute nodes?
   would a data bag be cleaner? perhaps a notification handler that automatically updates it?
   as soon as the new search syntax is supported, switch to that (available now)

** Document source of packages for all repos and break out to make them interchangeable

** librarian-chef for spiceweasel
** remotefilemirror->pxe_dust and others?
** Should we add kong and exerstack to the repo so people can validate their deployments?
** base role
   remove validator.pem?
   chef-client?
* Documentation
** Diagrams for Role/Cookbook relationships
   knife-spaghetti-roles
   Keystone
   Glance
   Nova
** Prerequisites for installation
   specifically with regards to network and operating system configuration
   lab-repo as a reference implementation
** Update the existing wiki documentation for Chef and OpenStack
** Chef for OpenStack QuickStart
** Desktop virtualization HOWTO
** Alternate package HOWTO
** Testing Overview
* Technical Roadmap
** LXC
** Swift
** Folsom Milestone 3
** HA setups
** Baremetal
** Hyper-V
** XenServer
** PostgreSQL
** Debian
** Fedora
** RHEL
** OpenSuSE/SLES
** IPv6
* Weekly Status 8/24
** Goals for next week:
*** prerequisites for networking documented
*** nova-compute vms failing during networking
*** nova-volume stop complaining
*** integrate Chef for OpenStack Hackday efforts
*** push openstack cookbooks to community site and Opscode github repos
*** start on the Quick Start for Chef and OpenStack
*** started work on Spiceweasel to make it Librarian-aware
** LA Chef for OpenStack Hackday
*** Prerequisites documentation (OS, network)
*** Support nova-network topologies
*** Desktop virtualization
*** Hypervisor breakout (KVM, LXC)
*** OpenStack-Syslog/Monitoring
*** RHEL/SUSE support
*** Ceph as nova-volumes/Cinder
*** Swift start
*** knife-openstack/hp/rackspace
*** Technical Debt!
** Cookbooks
*** database - need to test and update to 1.3.4
*** mysql - need to test and update to 1.3.0
*** osops-utils - mostly synced, a few minor patches ahead for debugging
*** sysctl - new dep, need to get upstreamed and documented
*** rabbitmq - fix for COOK-1496, waiting on RCB for a new rabbitmq::distro recipe
*** need to resync keystone, glance, nova and horizon with latest Rackspace patches


    added pm-utils
    bridge-utils!!!???

    mysql
    mysql -pvbyH4FV_6HTkiMntgHSC
    select id, host, hostname, display_name, access_ip_v4, task_state from instances;


    Device "eth0.100" does not exist
